[package]
name = "term3d"
version = "0.1.0"
authors = ["Luke Wilson <asmoaesl@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
easycurses = "0.12"
ordered-float = "1.0.1"
nalgebra-glm = "0.3.0"
